name: mentor_mesh_hub
version: 1.0.0+1
publish_to: none
description: MentorMesh Hub - A mentoring and learning platform.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependency_overrides:
  win32: ^4.1.3


dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  surf_lint_rules: ^2.1.0
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.0.2
  flutter_swipe_button: ^2.1.1+1
  syncfusion_flutter_charts: ^26.2.14
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  device_preview: ^1.1.0
  http: ^0.13.6
  shared_preferences: ^2.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Hanken Grotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
        - asset: assets/fonts/HankenGrotesk-ExtraLight.ttf
        - asset: assets/fonts/HankenGrotesk-Light.ttf
        - asset: assets/fonts/HankenGrotesk-Medium.ttf


